# Generated by Django 2.2 on 2020-12-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('see_basic', 'See Departments and Buildings'), ('see_experiments', 'See Experiments'), ('see_results', 'See Results'), ('see_tools', 'See Tools'), ('see_researchers', 'See Researchers')]},
        ),
    ]
