# Generated by Django 2.2 on 2020-12-20 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201216_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('see_basic', 'See Departments and Buildings'), ('see_experiments', 'See Experiments'), ('see_results', 'See Results'), ('see_tools', 'See Tools'), ('see_researchers', 'See Researchers'), ('add_basic', 'Add new Departments and Buildings'), ('add_experiments', 'Add mew Experiments'), ('add_results', 'Add new Results'), ('add_tools', 'Add new Tools'), ('add_researchers', 'Add new Researchers')]},
        ),
    ]
