# Generated by Django 2.2 on 2020-12-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_user_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('see_basic', 'See Departments and Buildings'), ('see_experiments', 'See Experiments'), ('see_results', 'See Results'), ('see_tools', 'See Tools'), ('see_researchers', 'See Researchers'), ('add_basic', 'Add new Departments and Buildings'), ('add_experiments', 'Add mew Experiments'), ('add_results', 'Add new Results'), ('add_tools', 'Add new Tools'), ('add_researchers', 'Add new Researchers'), ('modify_basic', 'Modify new Departments and Buildings'), ('modify_experiments', 'Modify mew Experiments'), ('modify_results', 'Modify new Results'), ('modify_tools', 'Modify new Tools'), ('modify_researchers', 'Modify new Researchers')]},
        ),
    ]
