# Generated by Django 2.2 on 2021-01-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20201221_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('see_basic', 'See Departments and Buildings'), ('see_experiments', 'See Experiments'), ('see_results', 'See Results'), ('see_tools', 'See Tools'), ('see_researchers', 'See Researchers'), ('add_basic', 'Add new Departments and Buildings'), ('add_experiments', 'Add new Experiments'), ('add_results', 'Add new Results'), ('add_tools', 'Add new Tools'), ('add_researchers', 'Add new Researchers'), ('remove_basic', 'Remove Departments and Buildings'), ('remove_experiments', 'Remove Experiments'), ('remove_results', 'Remove Results'), ('remove_tools', 'Remove Tools'), ('remove_researchers', 'Remove Researchers'), ('modify_basic', 'Modify Departments and Buildings'), ('modify_experiments', 'Modify Experiments'), ('modify_results', 'Modify Results'), ('modify_tools', 'Modify Tools'), ('modify_researchers', 'Modify Researchers')]},
        ),
    ]
